### ISSUE TITLE
Reactor redstone port

### ISSUE THREAD

**Issue by ghost** [RogueLogix/BiggerSeries#32] opened 2020-11-14 10:30 UTC
Hello,

I would like to automate my reactor with the redstone port.
I added two ports, one for output signal the other for receive signal.
I do it that way:
- Output = "Output - Energy amout" Active while below 90%
- Input = "Input - Control Rod Insertion" 
                Set on Signal 
                While on = 0%
                While off = 100%

I committed both redstone port but nothing happens on my reactor, rods don't change.
Maybe I am doing it wrong.
Sorry if my english is not perfect

**Comment by Topey2X** [comment] 2020-11-14 14:38
Hi Zackna, I've had a quick look in the commits and it seems there was a fix enabled in the last commit from RogueLogix.
If i were to guess, I'd say that it would be already fixed in the next version.
Came here to back you up but checked the commit history first :)

**Comment by ghost** [comment] 2020-11-14 14:52
Okay thanks, I will see in the next version.

**Comment by RogueLogix** [comment] 2020-11-14 19:26
That fix was specifically for this issue, AllTheMods/ATM-6#306.

Does that describe the issue here, or is it something different?

**Comment by RogueLogix** [comment] 2020-11-15 01:15
oh, i see what this is now, 475f3d3ddafe4f39ac49319341ae9aae94f71fa4 should have fixed this, as the problem is with the output while below 90%, rods should move as expected if using a lever

**Closed as completed** 2020-11-15 01:15 UTC
Labels: Reactor, BiggerReactors

**Comment by Lord-Volkner** [comment] 2022-03-13 05:17
A little off topic here, but what do I use to connect the two ports? In older versions, I've always used a rednet cable, but that doesn't exist in this modpack. What cable is used to connect the redstone ports?

**Comment by RogueLogix** [comment] 2022-03-13 05:25
redstone
